Primer commit
JohnDoe-LTD/ae1.dom.forms pull request #2
Opened 2022-11-01 17:28 UTC by tiznajo

Esta es mi primera rama de la actividad, no tiene CSS pero es completamente funcional con los requeriminetos de la actividad q

2022-11-01 18:02 UTC, aseguragonzalez requested changes

2022-11-01 18:02 UTC, aseguragonzalez commented on js/requerimiento2.js
> +    precio = precio + 10;
Podemos cambiar ```a = a + x``` por ```a +=  x```

2022-11-01 18:11 UTC, Dan17MAd submitted a review, later dismissed

2022-11-01 18:11 UTC, Dan17MAd commented on requerimento1.html
> +        Enunciado 1
Cambiamos la descripcion al readme

2022-11-01 18:11 UTC, Dan17MAd commented on requerimento1.html
> +        <div">
Eliminamos comillas.

2022-11-01 18:11 UTC, Dan17MAd commented on requerimento1.html
> +        <div">
Asignarle un ID al div

2022-11-01 18:11 UTC, Dan17MAd commented on js/requerimiento1.js
> +// Enunciado 1
Eliminar comentario, e incluirlo en README.

2022-11-01 18:11 UTC, Dan17MAd commented on js/requerimiento1.js
> +    document.body.appendChild(formulario);
El contenido se agregara en el div buscandolo por su id

2022-11-09 19:04 UTC, aseguragonzalez requested changes
Mover toto el contenido de la PR a una carpeta "propuesta" para que por lo menos quede guardado en el repo

2022-11-11 07:54 UTC, aseguragonzalez commented on js/requerimiento2.js
> +    precio = precio + 10;
Done!

2022-11-11 07:54 UTC, aseguragonzalez commented on js/requerimiento2.js
> +  if (radio1.checked || radio2.checked || radio3.checked) {
Done!

2022-11-11 07:57 UTC, aseguragonzalez commented on requerimento2.html
> +        <button onclick="todos()">¡Pedir pizza!</button>
Done!

2022-11-11 08:01 UTC, aseguragonzalez commented on requerimento2.html
> +            <input type="checkbox" id="checkbox1" value="atun"> Atún <br>
Done!

2022-11-11 08:03 UTC, aseguragonzalez commented on requerimento2.html
> +            <label>Dirección:</label> <br>
Done!

2022-11-11 08:05 UTC, aseguragonzalez commented on js/requerimiento1.js
> +    document.body.appendChild(formulario);
Done!

2022-11-11 08:09 UTC, aseguragonzalez commented on requerimento2.html
> +            <input type="radio" name="tamaño" id="pequeña" value="pequeña"> Pequeña <br>
Done!

2022-11-11 08:09 UTC, aseguragonzalez commented on requerimento2.html
> +            <label>Nombre</label> <br>
Se maqueta en una PR diferente

2022-11-11 08:10 UTC, aseguragonzalez approved these changes
Debatidos y resueltos los comentarios de la PR en pair

2022-11-11 08:11 UTC, merged